Repository smartdevicelink/sdl_evolution, pull requests merged in 2018-07, with the labels that each got.

#534 Revisions/0175 Updating DOP value range for GPS notification
  proposals/0175-Updating-DOP-value-range-for-GPS-notification.md
Labels: android, core, ios, review revision update, rpc

#523 Dismiss Alert RPC
  proposals/nnnn-dismiss-alert.md
Labels: android, core, ios, review ready, rpc

#535 Remove Hello SDL iOS Repository
  proposals/nnnn-remove-hello-sdl-ios.md
Labels: ios, review ready

#536 Template Titles
  proposals/nnnn-template-titles.md
Labels: android, core, ios, review ready, rpc

#537 Restructure iOS Threading and Queueing
  proposals/nnnn-restructure-ios-threading.md
Labels: ios, review ready

#544 Updates to App Services proposal [SDL-0167]
  proposals/0167-app-services.md
Labels: review revision update

#545 Interior Vehicle Data resumption
  proposals/nnnn-get-interior-data-resumption.md
Labels: core, hmi, review ready

#550 Update SDL-0183 (Automatic Mobile Resumption Hash Management) with requested revisions
  proposals/0183-mobile-hash-managment.md
Labels: android, ios, review ready, review revision update

#552 Restructuring OnResetTimeout
  proposals/NNNN-Restructuring-OnResetTimeout.md
Labels: core, review ready, rpc

#546 Handle response from HMI during resumption data
  assets/proposals/nnnn-resumption-data-error-handling/multiple_app_error_handling.png
  assets/proposals/nnnn-resumption-data-error-handling/multiple_app_error_handling_with_common_subscriptions.png
  proposals/nnnn-resumption-data-error-handling.md
Labels: core, review ready

#551 Retry Failed File Uploads
  proposals/nnnn-retry-failed-file-uploads.md
Labels: ios, review ready

#538 Accepted SDL behavior in case of LOW_VOLTAGE event: Resumption during Low Voltage
  proposals/0170-sdl-behavior-in-case-of-Low-Voltage.md
Labels: accepted, core, review revision update, rpc

#548 Revise SDL-0150 - Video Streaming State
  proposals/0150-video-streaming-state.md
Labels: android, core, ios, review ready, review revision update, rpc
