Repository smartdevicelink/sdl_evolution, pull requests merged in 2018-06, with the labels that each got.

#503 Deprecate RPCRequestFactory
  proposals/nnnn-deprecate-rpc-request-factory.md
Labels: android, review ready

#506 Updating DOP value range for GPS notification
  proposals/NNNN-Updating-DOP-value-range-for-GPS-notification.md
Labels: android, core, ios, review ready, rpc

#508 High level interface: Views and Controllers
  assets/proposals/NNNN-high-level-interface-views-and-controllers/view-controller-lifecycle.png
  proposals/NNNN-high-level-interface-views-and-controllers.md
Labels: ios, review ready

#512 Android Manager APIs
  proposals/0171-android-manager-apis.md
Labels: android, review revision update

#513 Alert icon
  proposals/nnnn-alert-icon.md
Labels: android, core, ios, review ready, rpc

#516 Revise Updating DOP value range for GPS notification
  proposals/0175-Updating-DOP-value-range-for-GPS-notification.md
Labels: android, core, ios, review ready, review revision update, rpc

#517 Interior Vehicle Data Subscription Management and Data Caching in SDL
  assets/proposals/nnnn-getInteriorVehicleData/GetInteriorVehicleData_current.png
  assets/proposals/nnnn-getInteriorVehicleData/GetInteriorVehicleData_new_subscribe.png
  proposals/NNNN-GetInteriorVehicleData.md
Labels: core, review ready, rpc

#518 [Revisions] High level interface: Views and Controllers
  proposals/0176-high-level-interface-views-and-controllers.md
Labels: ios, review ready, review revision update

#520 Pixel density and Scale
  proposals/NNNN-pixel-density-and-scale.md
Labels: android, core, ios, review ready, rpc

#505 App Service Update
  assets/proposals/0167-app-services/provider.png
  assets/proposals/0167-app-services/rpc_passthrough.png
  proposals/0167-app-services.md
Labels: android, core, ios, review ready

#521 Broaden Choice Uniqueness
  proposals/nnnn-broaden-choice-uniqueness.md
Labels: android, core, ios, review ready

#527 SDL shall not put RC applications to HMI level NONE when user disables RC in HMI
  proposals/NNNN-keep-rc-app-hmi-level-when-disable-rc.md
Labels: HMI, core, review ready

#528 Audio Source AM/FM/XM/DAB
  proposals/NNNN-audio-source-am-fm-xm.md
Labels: HMI, android, core, ios, review ready, rpc

#529 Automatic Mobile Resumption Hash Management
  proposals/nnnn-mobile-hash-managment.md
Labels: android, ios, review ready

#519 Remove 10 second timer from SDL-0122
  proposals/0122-New_rules_for_providing_VRHelpItems_VRHelpTitle.md
Labels: core, in review, review revision update
