Repository smartdevicelink/sdl_evolution, pull requests merged in 2018-03, with the labels that each got.

#414 Revisions: Allow clients to specify legacy nicknames
  proposals/0144-app-nicknames.md
Labels: android, core, ios, review ready, review revision update

#415 Revise "Supporting simultaneous multiple transports" proposal
  assets/proposals/0141-multiple-transports/0141-multiple-transports-class-diagram-android.png
  assets/proposals/0141-multiple-transports/0141-multiple-transports-class-diagram-core.png
  assets/proposals/0141-multiple-transports/0141-multiple-transports-class-diagram-ios.png
  proposals/0141-multiple-transports.md
Labels: android, core, ios, protocol, review ready, review revision update, rpc

#416 Revise "AOA multiplexing similar to Android BT/SPP multiplexing" proposal
  assets/proposals/0095-aoa-multiplexing-class-diagram.png
  proposals/0095-AOA-multiplexing.md
Labels: android, review ready, review revision update

#413 Updating Mobile Version Dependencies
  proposals/nnnn-updating-mobile-version-dependencies.md
Labels: meta, review ready

#419 Template Improvements: Color Scheme
  proposals/nnnn-template-color-scheme.md
Labels: android, core, ios, review ready, rpc

#420 Template Improvements: Additional SubMenus
  proposals/nnnn-template-additional-submenus.md
Labels: android, core, ios, review ready, rpc

#402 Add capability to disable or reject an app based on app type, transport type and OS type
  proposals/nnnn-mt-registration-limitation.md
Labels: android, core, ios, review ready, rpc

#417 Enhancing onHMIStatus with a New Parameter for Video Streaming State
  proposals/nnnn-video-streaming-state.md
Labels: android, core, ios, review ready, rpc

#418 ImageFieldName for SecondaryImage
  proposals/NNNN-imagefieldname-for-secondary-image.md
Labels: android, core, ios, review ready, rpc

#431 Driver Distraction Improvements: Command List Limitations
  proposals/nnnn-driver-distraction-list-limits.md
Labels: android, core, ios, review ready, rpc

#437 Support for Short and Full UUID App ID
  proposals/nnnn-support-short-long-appid.md
Labels: android, core, ios, review ready, rpc, shaid

#439 Add SDL Core Daemon script
  proposals/NNNN-add-sdl-core-daemon-script.md
Labels: core, review ready

#440 Mobile Menu Manager
  proposals/nnnn-mobile-menu-manager.md
Labels: android, ios, review ready
