Repository smartdevicelink/sdl_evolution, pull requests merged in 2018-08, with the labels that each got.

#547 Button Subscription response from HMI
  proposals/nnnn-button_subscription_response_from_hmi.md
Labels: core, hmi, review ready

#561 Update SDL-Android minimum SDK
  proposals/XXXX-update-android-min-sdk.md
Labels: android, review ready

#566 Revise SDL-0099 - New remote control modules
  proposals/0099-new-remote-control-modules-and-parameters.md
Labels: android, core, ios, review ready, review revision update, rpc

#560 Revise SDL-0041 - AppIcon Resumption
  proposals/0041-appicon-resumption.md
Labels: android, core, hmi, ios, review ready, review revision update

#576 Revise SDL-0184 Dismiss Alert
  proposals/0184-cancel-interaction.md
  proposals/0184-dismiss-alert.md
Labels: android, core, ios, review ready, review revision update, rpc

#495 Android Transport Overhaul
  assets/proposals/NNNN-android-transport-overhaul/TransportOverhaul_bridge.png
  assets/proposals/NNNN-android-transport-overhaul/TransportOverhaul_new.png
  assets/proposals/NNNN-android-transport-overhaul/TransportOverhaul_old.png
  proposals/NNNN-android-transport-overhaul.md
Labels: android, review ready

#572 Revise SDL-0099 - New remote control modules
  proposals/0099-new-remote-control-modules-and-parameters.md
Labels: android, core, ios, review ready, review revision update, rpc

#577 Revise SDL-0175 - Updating DOP value range for GPS notification
  proposals/0175-Updating-DOP-value-range-for-GPS-notification.md
Labels: accepted with revisions, android, core, ios, review revision update, rpc

#582 Update 0192-button_subscription_response_from_hmi.md
  proposals/0192-button_subscription_response_from_hmi.md
Labels: core, hmi, review revision update

#587 Add Support for Static Icons to SDLArtwork
  proposals/nnnn-sdlartwork-static-icons.md
Labels: android, ios, review ready

#578 Revise SDL-0153 Support for Short and Full UUID App ID
  proposals/0153-support-short-long-appid.md
Labels: android, core, ios, review ready, review revision update, rpc, shaid

#593 Update SDL-0118 with accepted revisions
  proposals/0118-video-background-string.md
Labels: android, ios, review revision update

#585 Revise SDL-0122 to exclude synonyms
  proposals/0122-New_rules_for_providing_VRHelpItems_VRHelpTitle.md
Labels: core, review ready, review revision update, rpc

#592 Update SetMediaClockTimer Initializers
  proposals/nnnn-setmediaclocktimer-initializers.md
Labels: android, ios, review ready

#594 Media Skip Indicators
  proposals/nnnn-media-skip-indicators.md
Labels: android, core, hmi, ios, review ready, rpc
