Repository smartdevicelink/sdl_evolution, pull requests merged in 2018-10, with the labels that each got.

#602 Removing URL Parameter Max Length
  proposals/NNNN-Removing-URL-Param-Max-Length.md
Labels: android, core, hmi, ios, review ready, rpc

#601 Revise SDL-0099 - Add a keepContextAvailable parameter and fix typos
  proposals/0099-new-remote-control-modules-and-parameters.md
Labels: android, core, hmi, ios, review ready, review revision update, rpc

#604 Remove defvalue from keepContext
  proposals/0099-new-remote-control-modules-and-parameters.md
Labels: android, core, ios, review ready, review revision update, rpc

#605 Revise SDL-0071 - remove default value for parameter subscribe in RPC GetInteriorVehicleData
  proposals/0071-remote-control-baseline.md
Labels: accepted, core, review revision update, rpc

#567 High level interface: Overlay controllers
  proposals/NNNN-high-level-interface-overlay-controllers.md
Labels: ios, review ready

#610 Supported Character Sets
  proposals/nnnn-character-sets.md
Labels: android, core, ios, review ready, rpc
