Repository smartdevicelink/sdl_evolution, pull requests merged in 2018-12, with the labels that each got.

#613 Avoid Custom button subscription in case HMI incompatibility
  proposals/NNNN-Avoid_custom_button_subscription_when_HMI_does_not_support.md
Labels: core, review ready

#622 Remote Automated testing
  assets/proposals/nnnn-hmi-relay/ATFRemoteAdapter.png
  proposals/nnnn-remote_atf_testing.md
Labels: review ready

#623 RPC message protection
  proposals/NNNN-rpc-message-protection.md
Labels: android, core, ios, policy server, review ready, rpc

#624 Block Old SDL Head Units from Mobile
  proposals/nnnn-block-sdl-head-units.md
Labels: android, cloud, ios, review ready

#625 Static Icon Capability
  proposals/nnnn-static-icon-capability.md
Labels: hmi, review ready, rpc

#627 Mobile Manager Dynamic Menu Cell Updating
  proposals/nnnn-mobile-dynamic-menu-cell-updating.md
Labels: android, cloud, ios, review ready

#629 Update SDL-0202 with review revisions
  proposals/0202-character-sets.md
Labels: android, core, ios, review ready, rpc

#639 High Level Interface: Overlay Controller (revision)
  proposals/0201-high-level-interface-overlay-controllers.md
Labels: ios, review ready

#630 Service Status Update to HMI
  assets/proposals/NNNN-ServiceStatusUpdateToHMI/Invalid-Cert.png
  assets/proposals/NNNN-ServiceStatusUpdateToHMI/PTU-Time-Out.png
  assets/proposals/NNNN-ServiceStatusUpdateToHMI/invalid-system-time.png
  assets/proposals/NNNN-ServiceStatusUpdateToHMI/sunny-day-scenario.png
  proposals/NNNN-ServiceStatusUpdateToHMI.md
Labels: core, review ready, rpc

#631 Add Ability to Reuse a SyncFileName for a PutFile
  proposals/nnnn-add-ability-to-reuse-a-syncfilename-for-a-putfile.md
Labels: core, review ready

#628 Secondary Transport Optimization
  proposals/0141-multiple-transports.md
  proposals/nnnn-secondary-transport-optimization.md
Labels: review ready

#644 Avoid Custom button subscription in case HMI incompatibility (revision)
  proposals/0205-Avoid_custom_button_subscription_when_HMI_does_not_support.md
Labels: review ready

#645 SDL 0206 - Remote Automated testing(revisions)
  proposals/0206-remote_atf_testing.md
Labels: review ready

#646 0173-Read-Generic-Network-Signal-data.md
  proposals/0173-Read-Generic-Network-Signal-data.md
Labels: review ready
