Repository smartdevicelink/sdl_evolution, pull requests merged in 2018-04, with the labels that each got.

#433 High Level Interface: Foundation
  assets/proposals/NNNN-high-level-interface-foundation/application-lifecycle.png
  assets/proposals/NNNN-high-level-interface-foundation/view-controller-lifecycle.png
  assets/proposals/NNNN-high-level-interface-foundation/view-controller-overview.png
  proposals/NNNN-high-level-interface-foundation.md
Labels: ios, review ready

#436 SDL Passenger Mode
  .DS_Store
  proposals/.DS_Store
  proposals/NNNN-SDL-passenger-mode.md
Labels: android, core, ios, review ready, rpc

#438 Mobile Choice Set Manager
  proposals/nnnn-mobile-choice-manager.md
Labels: android, ios, review ready

#446 Enhancing onHMIStatus with a New Parameter for Video Streaming State
  proposals/0150-video-streaming-state.md
Labels: android, core, ios, review ready, review revision update, rpc

#447 Revise SDL 0149 "Add capability to disable resumption based on app type and transport type"
  proposals/0149-mt-registration-limitation.md
Labels: core, review ready, review revision update

#434 Accepted multiple transport proposal: Addition of ini entry and amending header of Register Secondary Transport NAK
  proposals/0141-multiple-transports.md
Labels: core, protocol, review ready, review revision update

#450 Revised proposal of "AOA multiplexing similar to Android BT/SPP multiplexing"
  assets/proposals/0095-AOA-multiplexing/0095-aoa-multiplexing-class-diagram.png
  assets/proposals/0095-AOA-multiplexing/0095-aoa-possible-permanent-routerservice-solution.png
  proposals/0095-AOA-multiplexing.md
Labels: android, review ready, review revision update

#451 Cloud App Transport Adapter
  assets/proposals/nnnn-cloud-app-transport-adapter/web_app_high_level.png
  assets/proposals/nnnn-cloud-app-transport-adapter/web_app_ign_on.png
  assets/proposals/nnnn-cloud-app-transport-adapter/web_app_ptu.png
  assets/proposals/nnnn-cloud-app-transport-adapter/web_app_user_refresh.png
  proposals/nnnn-cloud-app-transport-adapter.md
Labels: core, review ready

#458 Choice-VR optional (revision)
  proposals/0064-choice-vr-optional.md
Labels: android, core, ios, review ready, review revision update, rpc

#459 Revise Support for Short and Full UUID App ID
  proposals/0153-support-short-long-appid.md
Labels: android, core, ios, review ready, review revision update, rpc, shaid

#460 Static SDL Icon Names Enum
  proposals/NNNN-Static-SDL-Icon-Names-Enum.md
Labels: android, ios, review ready

#461 Remote Control Radio Parameter Update
  proposals/NNNN-rc-radio-parameter-update.md
Labels: android, core, ios, review ready, rpc

#462 Remove SmartDeviceLink Cordova plugin
  proposals/nnnn-remove-sdl-cordova.md
Labels: android, ios, review ready

#466 Define Handling of Duplicate Correlation IDs
  proposals/NNNN-define-handling-of-duplicate-correlation-ids.md
Labels: core, protocol, review ready

#467 Make spaceAvailable field non-mandatory
  proposals/NNNN-make-spaceavailable-field-non-mandatory.md
Labels: review ready, rpc

#471 Modernize Ubuntu Support
  proposals/NNNN-modernize-ubuntu-support.md
Labels: core, review ready

#472 Update 0158-cloud-app-transport-adapter.md with revisions
  assets/proposals/0158-cloud-app-transport-adapter/cloud_app_activation.png
  assets/proposals/0158-cloud-app-transport-adapter/set_cloud_app_properties.png
  proposals/0158-cloud-app-transport-adapter.md
Labels: core, review ready, review revision update

#473 Remote Control – Lights – More Names and Status Values
  proposals/NNNN-rc-lights-more-names-and-status-values.md
Labels: android, core, ios, review ready, rpc
