Repository smartdevicelink/sdl_evolution, pull requests merged in 2018-02, with the labels that each got.

#403 Revise SDL 0138: Make 'audioPassThruCapabilities' of HMI an array
  proposals/0138-hmi-audiopassthru-capability.md
Labels: core, review ready, review revision update, rpc

#397 Supporting simultaneous multiple transports
  assets/proposals/nnnn-multiple-transports/nnnn-multiple-transports-class-diagram-android.png
  assets/proposals/nnnn-multiple-transports/nnnn-multiple-transports-class-diagram-core.png
  assets/proposals/nnnn-multiple-transports/nnnn-multiple-transports-class-diagram-ios.png
  proposals/nnnn-multiple-transports.md
Labels: android, core, ios, protocol, review ready, rpc

#399 Addition of 'App Instance ID' and 'Core Instance ID'
  proposals/nnnn-mt-instance-ids.md
Labels: android, core, ios, protocol, review ready

#401 Add Service Discovery mechanism for TCP transport
  proposals/nnnn-mt-service-discovery.md
Labels: android, core, ios, review ready

#408 Allow clients to specify legacy nicknames
  proposals/NNNN-app-nicknames.md
Labels: android, core, ios, review ready

#409 Driver Distraction Notification Upon Registration
  proposals/nnnn-distraction-notification-after-registration.md
Labels: core, review ready
