Repository smartdevicelink/sdl_evolution, pull requests merged in 2018-05, with the labels that each got.

#474 Use Android Annotations Library
  proposals/nnnn-use-android-annotations-library.md
Labels: android, review ready

#481 App Services
  assets/proposals/NNNN-app-services/consumer.png
  assets/proposals/NNNN-app-services/file_transfer.png
  assets/proposals/NNNN-app-services/provider.png
  proposals/nnnn-app-services.md
Labels: android, core, ios, review ready

#482 RPC design refactoring
  assets/proposals/nnnn-rpc-design-refactoring/new_design.png
  proposals/nnnn-rpc-design-refactoring.md
Labels: core, review ready

#332 SDL behavior in case of LOW_VOLTAGE event
  proposals/nnnn-sdl-behavior-in-case-of-Low-Voltage_mqueue.md
Labels: core, review ready, rpc

#469 Accepted handling VR help requests proposal: Conditions for using the default values for helpPrompt and vrHelp parameters and update the default value for vrHelp in ini file
  proposals/0122-New_rules_for_providing_VRHelpItems_VRHelpTitle.md
Labels: core, protocol, review ready, review revision update

#470 High Level Interface - Foundation (revision)
  proposals/0156-high-level-interface-foundation.md
Labels: ios, review ready, review revision update

#490 AOA multiplexing for Android Proxy
  assets/proposals/0095-AOA-multiplexing/0095-aoa-multiplexing-class-diagram.png
  assets/proposals/0095-AOA-multiplexing/0095-multiplex_for_multiple_transports.png
  proposals/0095-AOA-multiplexing.md
Labels: android, review ready, review revision update

#491 Revisions/0158 cloud app transport adapter
  assets/proposals/0158-cloud-app-transport-adapter/cloud_app_activation.png
  assets/proposals/0158-cloud-app-transport-adapter/example_use_case_1.png
  assets/proposals/0158-cloud-app-transport-adapter/example_use_case_2.png
  assets/proposals/0158-cloud-app-transport-adapter/example_use_case_3.png
  assets/proposals/0158-cloud-app-transport-adapter/example_use_case_4.png
  assets/proposals/0158-cloud-app-transport-adapter/set_cloud_app_properties.png
  proposals/0158-cloud-app-transport-adapter.md
Labels: core, review ready, review revision update

#498 Remote Control - Update OnRCStatus with a new allowed parameter
  proposals/NNNN-onRcStatus-allowed.md
Labels: android, core, ios, review ready, rpc

#499 Read Generic Network Signal data
  proposals/NNNN-Read-Generic-Network-Signal-data.md
Labels: android, core, ios, review ready, rpc
