Repository smartdevicelink/sdl_evolution, pull requests merged in 2019-07, with the labels that each got.

#772 Commerce App Service
  proposals/NNNN-Commerce-App-Service.md
Labels: core, ios, java suite, review ready, rpc

#773 Subtle Alert Style
  assets/proposals/nnnn-alert-style-subtle/subtle-alert-mockup.png
  proposals/nnnn-alert-style-subtle.md
Labels: core, hmi, ios, java suite, review ready, rpc

#774 Revisions 0238 Keyboard Enhancements
  proposals/0238-Keyboard-Enhancements.md
Labels: core, ios, java suite, review ready, review revision update, rpc

#775 Revise SDL-0119 SDL Passenger Mode
  proposals/0119-SDL-passenger-mode.md
Labels: core, ios, java suite, review ready, review revision update, rpc, sdl policy server

#781 Another revision SDL-0230: SPP resource management
  assets/proposals/0230-spp-resource-management-for-android/spp_error_activity.png
  proposals/0230-spp-resource-management-for-android.md
Labels: java suite, review ready, review revision update

#782 Revise - WebEngine support for SDL JavaScript
  proposals/0240-sdl-js-pwa.md
Labels: core, javascript, review ready, review revision update, rpc, sdl policy server

#780 Revise SDL-0108 AutoCompleteList
  proposals/0108-AutoCompleteList.md
Labels: core, ios, java suite, review ready, review revision update, rpc

#779 Revise SDL-0186 Template Titles
  proposals/0186-template-titles.md
Labels: core, ios, java suite, review ready, review revision update, rpc

#764 Revision 0173-Read-Generic-Network-Signal-data.md
  assets/proposals/0173-Read-Generic-Network-Signal-data/OEM Mapping table update flow.png
  assets/proposals/0173-Read-Generic-Network-Signal-data/SDL-HMI request response flow.png
  assets/proposals/0173-Read-Generic-Network-Signal-data/Schema_Version_Update_flow.png
  proposals/0173-Read-Generic-Network-Signal-data.md
Labels: core, ios, java suite, review ready, review revision update, rpc

#789 Manager Update for DisplayCapability
  proposals/NNNN-manager-update-display-capability.md
Labels: ios, java suite, review ready

#790 Custom Playback Rates for SetMediaClockTimer
  proposals/nnnn-setmediaclocktimer-custom-playback-rates.md
Labels: core, hmi, ios, java suite, review ready, rpc

#794 WiFi Transport: Sharing SSID and password with Mobile Proxy
  proposals/NNNN-sharing-wifi-ssid-and-password.md
Labels: core, hmi, ios, java suite, review ready, rpc
