Repository smartdevicelink/sdl_evolution, pull requests merged in 2019-12, with the labels that each got.

#849 SDL-0234 Proxy Library RPC Generation - Revision
  proposals/0234-proxy-rpc-generation.md
Labels: ios, java suite, javascript, review ready, review revision update

#878 SDL-0240 - WebEngine support for SDL JavaScript - Revision
  proposals/0240-sdl-js-pwa.md
Labels: core, javascript, review ready, review revision update, rpc, sdl policy server

#837 New vehicle data GearStatus
  proposals/NNNN-New-vehicle-data-GearStatus.md
Labels: core, hmi, ios, java suite, review ready, rpc, sdl policy server, shaid

#874 Main Menu UI Updates
  proposals/nnnn-addcommand-ui-updates.md
Labels: core, hmi, ios, java suite, review ready, rpc

#876 Main Menu Updating and Pagination
  proposals/nnnn-main-menu-updating.md
Labels: core, hmi, ios, java suite, review ready, rpc

#838 New vehicle data ClimateData
  proposals/NNNN-New-vehicle-data-ClimateData.md
Labels: core, hmi, ios, java suite, review ready, rpc, sdl policy server, shaid

#880 Add means to launch with optimum appHMIType
  proposals/NNNN-Add-means-to-launch-with-optimum-appHMIType.md
Labels: core, hmi, ios, java suite, review ready, rpc

#889 Start APT of SDL App by pressing PTT button
  proposals/NNNN-Start-APT-of-SDL-App-by-pressing-PTT-Button.md
Labels: core, hmi, ios, java suite, review ready

#866 SDL 0259 - Disabled Softbuttons
  assets/proposals/0259-Disabled-Softbuttons/iheartRadio1.PNG
  assets/proposals/0259-Disabled-Softbuttons/iheartRadio2.PNG
  proposals/0259-DisabledSoftbuttons.md
Labels: core, ios, java suite, review ready, review revision update, rpc

#868 0250 Next RPC Indication for the HMI
  proposals/0250-NextRpcIndication.md
Labels: core, ios, java suite, review ready, review revision update, rpc

#894 Revised New vehicle data GearStatus
  proposals/0266-New-vehicle-data-GearStatus.md
Labels: core, hmi, ios, java suite, review ready, review revision update, rpc, sdl policy server, shaid

#897 Requested revisions for SDL-0268 Main Menu Updating and Pagination
  proposals/0268-main-menu-updating.md
Labels: core, hmi, ios, java suite, review ready, review revision update, rpc

#898 JavaScript Suite SDL Manager
  proposals/nnnn-sdl-javascript-manager-layer.md
Labels: javascript, review ready
