Repository smartdevicelink/sdl_evolution, pull requests merged in 2019-11, with the labels that each got.

#839 New vehicle data HandsOffSteering
  proposals/NNNN-New-vehicle-data-HandsOffSteering.md
Labels: core, hmi, ios, java suite, review ready, rpc, sdl policy server, shaid

#840 Update vehicle data TurnSignal
  proposals/NNNN-Update-vehicle-data-TurnSignal.md
Labels: core, hmi, ios, java suite, review ready, rpc

#848 Disabled Softbuttons
  proposals/NNNN-DisabledSoftbuttons.md
Labels: core, ios, java suite, review ready, rpc

#852 Deprecate HMI RPC OnFindApplications
  proposals/NNNN-Deprecate-HMI-RPC-OnFindApplications.md
Labels: core, review ready

#862 Revised Enhance BodyInformation vehicle data
  proposals/0255-Enhance-BodyInformation-vehicle-data.md
Labels: core, hmi, ios, java suite, review ready, review revision update, rpc

#835 New vehicle data WindowStatus
  proposals/NNNN-New-vehicle-data-WindowStatus.md
Labels: core, hmi, ios, java suite, review ready, rpc, sdl policy server, shaid

#836 New vehicle data SeatOccupancy
  proposals/NNNN-New-vehicle-data-SeatOccupancy.md
Labels: core, hmi, ios, java suite, review ready, rpc, sdl policy server, shaid

#863 Extend SystemRequest With Optional Data For Proprietary Data Exchange
  proposals/NNNN-System-Request.md
Labels: core, ios, java suite, review ready, rpc

#864 Adding Audible Status Notification
  proposals/NNNN-Adding-Audible-Status-Notification.md
Labels: core, hmi, review ready, rpc

#867 Remove duplicate parameter FileName from HMI RPC BasicCommunication.OnPutFile
  proposals/NNNN-Remove-Duplicate-Parameter-HMI-RPC-OnPutFile.md
Labels: core, review ready
