Repository smartdevicelink/sdl_evolution, pull requests merged in 2019-04, with the labels that each got.

#696 Remote Control - Allow Multiple Modules per Module Type
  assets/proposals/nnnn-multiple-modules/2x3.jpg
  assets/proposals/nnnn-multiple-modules/3x3.jpg
  assets/proposals/nnnn-multiple-modules/4x4.jpg
  proposals/nnnn-multiple-modules.md
Labels: android, core, ios, review ready, rpc

#699 Add System Software Name parameter to Register App Interface Response
  proposals/nnnn-rair-system-software-name.md
Labels: android, core, ios, review ready, rpc

#705 Revise SDL 0220: support for Android custom RouterService
  proposals/0220-support-for-android-custom-routerservice.md
Labels: android, review ready, review revision update

#703 Add Currently Playing Media Image to MediaServiceData
  proposals/nnnn-media-service-image.md
Labels: android, cloud proxy, core, ios, review ready, rpc

#709 Navigation Subscription Buttons
  proposals/nnnn-navigation-subscription-buttons.md
Labels: core, hmi, ios, java suite, review ready, rpc

#710 Update Published App Services
  proposals/NNNN-update-published-app-services.md
Labels: core, ios, java suite, policy server, review ready, rpc, shaid

#711 Add iOS SDLManager RPC Subscriptions
  proposals/nnnn-ios-manager-rpc-subscriptions.md
Labels: ios, review ready
