Repository smartdevicelink/sdl_evolution, pull requests merged in 2019-10, with the labels that each got.

#822 Revise 0173-Read-Generic-Network-Signal-data.md
  proposals/0173-Read-Generic-Network-Signal-data.md
Labels: core, review ready, review revision update

#824 Next RPC Indication for the HMI
  assets/proposals/NNNN-NextRpcIndication/NNNN-NextRpcIndication.png
  proposals/NNNN-NextRpcIndication.md
Labels: core, ios, java suite, review ready, rpc

#825 Font Styles
  assets/proposals/NNNN-font-styles/NNNN-font-styles.png
  proposals/NNNN-font-styles.md
Labels: core, ios, java suite, review ready, rpc

#826 Aligning HMI and MOBILE API for pcmStreamCapabilities
  proposals/NNNN-Aligning-HMI-and-MOBILE-API-for-pcmStreamCapabilities.md
Labels: core, hmi, review ready

#832 New vehicle data StabilityControlsStatus
  proposals/NNNN-New-vehicle-data-StabilityControlsStatus.md
Labels: core, hmi, ios, java suite, review ready, rpc, sdl policy server, shaid

#833 New vehicle data HVBatteryLevel
  proposals/NNNN-New-vehicle-data-HVBatteryLevel.md
Labels: core, hmi, ios, java suite, review ready, rpc, sdl policy server, shaid

#846 Font Styles
  proposals/0251-font-styles.md
Labels: core, ios, java suite, review ready, review revision update, rpc

#851 Refactor Fuel Information Related Vehicle Data
  proposals/NNNN-Refactor-Fuel-Information-Related-Vehicle-Data.md
Labels: core, hmi, ios, java suite, review ready, rpc
