Repository smartdevicelink/sdl_evolution, pull requests merged in 2019-08, with the labels that each got.

#786 Revise SDL-0221 Remote Control - Allow Multiple Modules per Module Type
  proposals/0221-multiple-modules.md
Labels: core, ios, java suite, review ready, review revision update, rpc

#788 SDL 0216 - Widget Support (Revision)
  proposals/0216-widget-support.md
Labels: core, ios, java suite, review ready, review revision update, rpc

#795 SDL 0231 Menu Tiles Revision
  proposals/0231-main-menu-tiles.md
Labels: core, hmi, ios, java suite, review ready, review revision update, rpc

#796 Revise SDL 0237 Add Feature to Disable "Video Streaming Backgrounded String" Feature
  proposals/0237-add-feature-to-disable-video-streaming-backgrounded-string-feature.md
Labels: ios, review ready, review revision update

#803 Add App Services to HMICapabilities
  proposals/NNNN-app-services-hmi_capabilities.md
Labels: core, ios, java suite, javascript, review ready, rpc

#802 [SDL 0173] - Read Generic Network Signal Data Clarification
  proposals/0173-Read-Generic-Network-Signal-data.md
Labels: core, hmi, ios, java suite, review ready, review revision update, rpc, sdl policy server, shaid

#810 SDL-0240 Revision - WebEngine support for SDL JavaScript
  assets/proposals/0240-sdl-js-pwa/web-app-example.jpg
  proposals/0240-sdl-js-pwa.md
Labels: core, javascript, review ready, review revision update, rpc, sdl policy server

#765 SDL Server 3.0.0 (refactor)
  proposals/NNNN-sdl-server-3.md
Labels: review ready, sdl policy server

#804 HMI Policy Table Update using vehicle modem
  assets/proposals/NNNN-hmi-ptu-support/diagram_ptu_external_proprietary.png
  assets/proposals/NNNN-hmi-ptu-support/diagram_ptu_external_proprietary_enhanced.png
  assets/proposals/NNNN-hmi-ptu-support/diagram_ptu_external_proprietary_enhanced_fallback.png
  proposals/NNNN-hmi-ptu-support.md
Labels: core, hmi, review ready
