Repository smartdevicelink/sdl_evolution, pull requests merged in 2019-05, with the labels that each got.

#698 Widget support revisions
  assets/proposals/0216-widget-support/hmi-chart.png
  proposals/0216-widget-support.md
Labels: core, ios, java suite, review ready, review revision update, rpc

#716 Revision of SDL-221 Remote Control - Allow Multiple Modules per Module Type
  proposals/0221-multiple-modules.md
Labels: core, ios, java suite, review ready, review revision update, rpc

#717 Add Supported RGB Colors to Light Capabilities
  proposals/nnnn-add-supported-rgb-colors.md
Labels: core, ios, java suite, review ready, rpc

#718 SDL Server Email Notifications
  assets/proposals/NNNN-sdl-server-email-notifications/email-preview.jpg
  assets/proposals/NNNN-sdl-server-email-notifications/visual-config-preview.png
  proposals/NNNN-sdl-server-email-notifications.md
Labels: review ready, sdl policy server

#719 SDL Server Version Tracking
  proposals/NNNN-sdl-server-version-tracking.md
Labels: review ready, sdl policy server, shaid

#715 SPP resource management for android
  proposals/NNNN-spp-resource-management-for-android.md
Labels: java suite, review ready

#725 Revise for SDL-0220: Support for Android custom RouterService
  proposals/0220-support-for-android-custom-routerservice.md
Labels: java suite, review ready, review revision update

#726 Add Tiles as an Option for Main Menus
  proposals/nnnn-main-menu-tiles.md
Labels: core, hmi, ios, java suite, review ready, rpc

#727 Add Pushing Buffer Support to AudioStreamManager
  proposals/nnnn-add_pushing_buffer_support_to_audio_stream_manager.md
Labels: ios, java suite, review ready

#682 Revise SDL-0189 to remove UI/TTS OnResetTimeout and remove range for requested
  proposals/0189-Restructuring-OnResetTimeout.md
Labels: accepted with revisions

#736 SDL Server Statistics Recording & Visualizations
  proposals/NNNN-policy-server-statistics-recording-visualizations.md
Labels: core, review ready, sdl policy server

#737 Proxy Library RPC Generation
  proposals/nnnn-proxy-rpc-generation.md
Labels: ios, java suite, review ready

#738 SDL JavaScript library
  proposals/NNNN-sdl-js-library.md
Labels: review ready

#739 Update mismatch in TireStatus structure
  proposals/NNNN-TireStatus-Mismatch.md
Labels: core, ios, java suite, review ready, rpc
