Repository smartdevicelink/sdl_evolution, pull requests merged in 2019-06, with the labels that each got.

#746 Add Feature to Disable "Video Streaming Backgrounded String" Feature
  proposals/XXXX-add-feature-to-disable-video-streaming-backgrounded-string-feature.md
Labels: ios, review ready

#747 Keyboard Enhancements
  assets/proposals/nnnn-keyboard-enhancements/azerty_special_chars.png
  assets/proposals/nnnn-keyboard-enhancements/numeric_keypad.png
  assets/proposals/nnnn-keyboard-enhancements/qwerty_special_chars.png
  proposals/NNNN-Keyboard-Enhancements.md
Labels: core, ios, java suite, review ready, rpc

#748 Revise SDL 0230: SPP resource management for Android
  assets/proposals/0230-spp-resource-management-for-android/manage_notification_1.png
  assets/proposals/0230-spp-resource-management-for-android/manage_notification_2.png
  assets/proposals/0230-spp-resource-management-for-android/spp_error_activity.png
  assets/proposals/0230-spp-resource-management-for-android/spp_notification_popup.png
  proposals/0230-spp-resource-management-for-android.md
Labels: java suite, review ready, review revision update

#749 Media Service Data Progress Bar Improvements
  proposals/xxx-media-service-data-progress-bar-improvements.md
Labels: core, ios, java suite, review ready, rpc

#750 Update to SDL0211 - Service Status Update to HMI
  proposals/0211-ServiceStatusUpdateToHMI.md
Labels: core, review ready, review revision update, rpc

#752 WebEngine support for SDL JavaScript
  assets/proposals/NNNN-sdl-js-pwa/activate-web-app.png
  assets/proposals/NNNN-sdl-js-pwa/arch-overview.png
  assets/proposals/NNNN-sdl-js-pwa/web-app-example.jpg
  proposals/NNNN-sdl-js-pwa.md
Labels: core, javascript, review ready, rpc, sdl policy server

#757 Revision 0213-rc-radio-climate-parameter-update
  proposals/0213-rc-radio-climate-parameter-update.md
Labels: core, ios, java suite, review ready, review revision update, rpc

#770 Revise SDL-0230: SPP resource management for Android
  assets/proposals/0230-spp-resource-management-for-android/spp_error_activity.png
  assets/proposals/0230-spp-resource-management-for-android/spp_notification_popup.png
  proposals/0230-spp-resource-management-for-android.md
Labels: java suite, review ready, review revision update

#766 Revise 0119-SDL-passenger-mode.md
  proposals/0119-SDL-passenger-mode.md
Labels: core, ios, java suite, review ready, review revision update, rpc, sdl policy server
