Repository smartdevicelink/sdl_evolution, pull requests merged in 2020-05, with the labels that each got.

#996 Revise SDL-0273 Webengine projection mode.
  assets/proposals/0273-webengine-projection-mode/web-app-example.jpg
  assets/proposals/0273-webengine-projection-mode/web-app-example_with_exit_button_and_template_title.jpg
  assets/proposals/0273-webengine-projection-mode/web-app-example_with_outside_menu_and_template_title.jpg
  proposals/0273-webengine-projection-mode.md
Labels: core, javascript, review ready, review revision update

#1006 Revise 0298-Processing of unknown enum values by SDL Core
  proposals/0298-Processing-of-unknown-enum-values-by-SDL-and-Mobile-libraries.md
Labels: core, review ready, review revision update

#946 SDL Audio IO Manager
  assets/proposals/nnnn-audio-io-manager/SDLAudioIOManager.h
  assets/proposals/nnnn-audio-io-manager/SDLAudioIOManager.m
  assets/proposals/nnnn-audio-io-manager/SDLAudioIOManagerDelegate.h
  proposals/nnnn-audio-io-manager.md
Labels: ios, review ready

#947 Start Video Stream With OnTouchEvent Permission
  proposals/nnnn-stream-ontouchevent.md
Labels: ios, review ready

#981 WiFi Transport: Sharing SSID and password with Mobile Proxy
  assets/proposals/0245-sharing-wifi-ssid-and-password/WiFi_AP_created_manually_Disconnected.png
  assets/proposals/0245-sharing-wifi-ssid-and-password/WiFi_AP_created_manually_Disconnected.puml
  assets/proposals/0245-sharing-wifi-ssid-and-password/andoid_permissions.png
  assets/proposals/0245-sharing-wifi-ssid-and-password/minimal_approach.png
  assets/proposals/0245-sharing-wifi-ssid-and-password/minimal_approach.puml
  assets/proposals/0245-sharing-wifi-ssid-and-password/mobile_access_point.png
  assets/proposals/0245-sharing-wifi-ssid-and-password/mobile_access_point.puml
  assets/proposals/0245-sharing-wifi-ssid-and-password/mobile_access_point_multidev_externalhost.png
  assets/proposals/0245-sharing-wifi-ssid-and-password/mobile_access_point_multidev_externalhost.puml
  assets/proposals/0245-sharing-wifi-ssid-and-password/secure_service.png
  assets/proposals/0245-sharing-wifi-ssid-and-password/secure_service.puml
  assets/proposals/0245-sharing-wifi-ssid-and-password/vehicle_access_point.png
  assets/proposals/0245-sharing-wifi-ssid-and-password/vehicle_access_point.puml
  assets/proposals/0245-sharing-wifi-ssid-and-password/vehicle_access_point_multiapps.png
  assets/proposals/0245-sharing-wifi-ssid-and-password/vehicle_access_point_multiapps.puml
  assets/proposals/0245-sharing-wifi-ssid-and-password/vehicle_access_point_multidev.png
  assets/proposals/0245-sharing-wifi-ssid-and-password/vehicle_access_point_multidev.puml
  proposals/0245-sharing-wifi-ssid-and-password.md
Labels: core, hmi, ios, java suite, review ready, review revision update, rpc

#1008 Homogenize TextFieldName
  proposals/XXXX-homogenize-textfieldname.md
Labels: core, hmi, ios, java suite, javascript, review ready, rpc

#1019 Use Taskmaster To Handle Queuing Operations in Managers
  proposals/nnnn-Use-Taskmaster-To-Handle-Queuing-Operations-In-Managers.md
Labels: java suite, review ready
