Repository smartdevicelink/sdl_evolution, pull requests merged in 2020-12, with the labels that each got.

#1101 Revise 0315 - Add RPC conflict management
  assets/proposals/0315-Add-RPC-Conflict-Management/Figure2_ONS_RPCs_conflict.png
  assets/proposals/0315-Add-RPC-Conflict-Management/Figure3_TTS_RPCs_conflict.png
  assets/proposals/0315-Add-RPC-Conflict-Management/Table4_Priority_result_of_Table3.png
  assets/proposals/0315-Add-RPC-Conflict-Management/Table_2_Priority_result_of_Table1.png
  proposals/0315-Add-RPC-Conflict-Management.md
Labels: core, hmi, review ready, sdl policy server

#1097 Modernize Ubuntu Support V20 LTS
  proposals/nnnn-modernize-ubuntu-support-v20.md
Labels: ATF, core, review ready

#1104 [Returned for Revisions] - SDL 0326 Handle Late Malformed Messages
  proposals/0326-handle-late-malformed-hmi-responses.md
Labels: core, hmi, review ready
