Repository smartdevicelink/sdl_evolution, pull requests merged in 2020-07, with the labels that each got.

#1042 SDL 0299 Revisions - Add a Mechanism to Avoid Deadlock
  proposals/0299-Avoid-Deadlock.md
Labels: ios, review ready, review revision update

#1015 Revise SDL-0278 - Screen Manager Template Management
  proposals/0278-screenmanager-layout-management.md
Labels: accepted, ios, java suite, javascript, review revision update

#1043 SDL 0280 Revisions - Adding new parameter of requires audio support and bluetoothDeviceAddress
  assets/proposals/0280-Adding-new-parameter-of-requiresAudioSupport-and-BluetoothDeviceAddress/registeringApp_flow.png
  proposals/0280-Adding-new-parameter-of-requiresAudioSupport-and-BluetoothDeviceAddress.md
Labels: core, hmi, ios, java suite, protocol, review ready, review revision update, rpc

#977 Mitigating Android SDL service notifications issues
  assets/proposals/NNNN-android-notifications/all_noti.png
  assets/proposals/NNNN-android-notifications/noti_button.png
  assets/proposals/NNNN-android-notifications/noti_button_1.png
  assets/proposals/NNNN-android-notifications/noti_button_2.png
  assets/proposals/NNNN-android-notifications/review_1.png
  assets/proposals/NNNN-android-notifications/review_2.png
  assets/proposals/NNNN-android-notifications/review_3.png
  assets/proposals/NNNN-android-notifications/sdl_faq.png
  assets/proposals/NNNN-android-notifications/waiting_for_connection.png
  proposals/NNNN-android-notifications.md
Labels: java suite, review ready

#993 Perform Interaction Multipick
  assets/proposals/NNNN-PerformInteraction-Multipick/PerformInteraction Multipick overview.PNG
  proposals/NNNN-PerformInteractionMultipick.md
Labels: core, hmi, ios, java suite, javascript, review ready, rpc

#1036 Make RPC Setters Chainable
  proposals/nnnn-Make-RPC-Setters-Chainable.md
Labels: java suite, review ready

#1050 Update the Minimum Required iOS Version to 10.0
  proposals/nnnn-ios-update-minimum-version-ios10.md
Labels: ios, review ready

#1040 Revise SDL-0242 Subtle Alert Style
  proposals/0242-alert-style-subtle.md
Labels: core, hmi, in review, ios, java suite, javascript, review revision update, rpc, sdl policy server

#1044 Revise 0268 Main Menu Updating
  proposals/0268-main-menu-updating.md
Labels: core, hmi, in review, ios, java suite, javascript, review revision update, rpc

#1045 Revise 0152-driver-distraction-list-limits
  proposals/0152-driver-distraction-list-limits.md
Labels: core, hmi, in review, ios, java suite, javascript, review revision update, rpc

#1007 Adding new parameters for transport switching
  proposals/XXXX-Adding-new-parameters-for-transport-switching.md
Labels: core, hmi, ios, java suite, javascript, review ready, rpc
