Repository smartdevicelink/sdl_evolution, pull requests merged in 2020-01, with the labels that each got.

#886 Revisions SDL-0245 WiFi Transport: Sharing SSID and password with Mobile Proxy
  proposals/0245-sharing-wifi-ssid-and-password.md
Labels: core, hmi, ios, java suite, review ready, review revision update, rpc

#902 Revision 0263 Extend SystemRequest With Optional Data For Proprietary Data Exchange
  proposals/0263-System-Request.md
Labels: core, ios, java suite, review ready, review revision update, rpc

#904 Revisions SDL-0264 Separating the change of Audible status and the change of HMI Status
  proposals/0264-Adding-Audible-Status-Notification.md
  proposals/0264-Separating-the-change-of-Audible-status-and-the-change-of-HMI-Status.md
Labels: core, hmi, review ready

#809 WebEngine Projection mode
  assets/proposals/NNNN-webengine-projection-mode/web-app-example.jpg
  proposals/NNNN-webengine-projection-mode.md
Labels: core, javascript, review ready

#890 Add preferred FPS to VideoStreamingCapability
  proposals/NNNN-add-preferred-FPS.md
Labels: core, ios, java suite, review ready, rpc

#906 WebEngine App Testing
  proposals/NNNN-webengine-app-testing.md
Labels: dev portal/manticore, review ready

#919 JavaScript Suite SDL Manager
  proposals/0272-sdl-javascript-manager-layer.md
Labels: javascript, review ready, review revision update
