Repository smartdevicelink/sdl_evolution, pull requests merged in 2020-04, with the labels that each got.

#960 Add function to transmit audio data of AudioStream in time division
  assets/proposals/NNNN-Add-function-to-transmit-audio-data/Image.gif
  proposals/NNNN-Add-function-to-transmit-audio-data.md
Labels: ios, java suite, review ready

#967 Processing of unknown enum values by SDL Core and Mobile Libraries
  proposals/NNNN-Processing-of-unknown-enum-values-by-SDL-and-Mobile-libraries.md
Labels: core, ios, java suite, review ready

#985 Requested Revisions for SDL 0294 - App Service Messaging
  proposals/0294-app-service-messaging.md
Labels: core, dev portal/manticore, hmi, ios, java suite, review ready, review revision update, rpc, sdl policy server

#986 Revise SDL-0234 - Proxy Library RPC Generation proposal - Keyword Avoidance
  proposals/0234-proxy-rpc-generation.md
Labels: core, ios, java suite, javascript, review ready, review revision update, rpc

#961 Add a mechanism to avoid Deadlock
  proposals/NNNN-Avoid-Deadlock.md
Labels: ios, review ready

#982 Voice Assistant App Service
  proposals/NNNN-Voice-Assistant-App-Service.md
Labels: core, hmi, ios, java suite, javascript, review ready, rpc

#998 SDL Device Listener
  assets/proposals/NNNN-SDL-device-listener/flow_chart.png
  proposals/NNNN-SDL-device-listener.md
Labels: java suite, review ready

#1002 SDL System Structure for Middle/Low-end Class Model of Powered Two Wheeler
  assets/proposals/NNNN-SDL-System-Structure-for-MiddleLow-end-Class-Model-of-Powered-Two-Wheeler/Figure1_Sample_of_a_simple_meter_display.png
  assets/proposals/NNNN-SDL-System-Structure-for-MiddleLow-end-Class-Model-of-Powered-Two-Wheeler/Figure2_SDL_System_for_Middle_Low_end_class.png
  assets/proposals/NNNN-SDL-System-Structure-for-MiddleLow-end-Class-Model-of-Powered-Two-Wheeler/Figure3_System_structure_of_proxy_and_meter_unit.png
  proposals/NNNN-SDL-System-Structure-for-MiddleLow-end-Class-Model-of-Powered-Two-Wheeler.md
Labels: core, hmi, ios, java suite, javascript, protocol, review ready, rpc, sdl policy server
