Repository smartdevicelink/sdl_evolution, pull requests merged in 2020-06, with the labels that each got.

#992 Get Input Screen
  assets/proposals/NNNN-GetInput/GetInput Overview.PNG
  assets/proposals/NNNN-GetInput/GetInput-1-1.PNG
  assets/proposals/NNNN-GetInput/GetInput-1-2.PNG
  assets/proposals/NNNN-GetInput/GetInput-1.PNG
  assets/proposals/NNNN-GetInput/GetInput-2.PNG
  assets/proposals/NNNN-GetInput/GetInput-3-1.PNG
  assets/proposals/NNNN-GetInput/GetInput-3-2.PNG
  assets/proposals/NNNN-GetInput/GetInput-3.PNG
  proposals/NNNN-GetInputScreen.md
Labels: core, hmi, ios, java suite, javascript, review ready, rpc

#997 revised SDL-0280
  assets/proposals/0280-Adding-new-parameter-of-requiresAudioSupport-and-BluetoothDeviceAddress/registeringApp_flow.png
  assets/proposals/0280-Adding-new-parameter-of-requiresAudioSupport-and-BluetoothDeviceAddress/registeringApp_flow1.png
  assets/proposals/0280-Adding-new-parameter-of-requiresAudioSupport-and-BluetoothDeviceAddress/registeringApp_flow2.png
  proposals/0280-Adding-new-parameter-of-requiresAudioSupport-and-BluetoothDeviceAddress.md
Labels: core, hmi, ios, java suite, protocol, review ready, review revision update, rpc

#1009 Add a Reason Parameter to All Protocol NAKs
  proposals/nnnn-protocol-nak-reason.md
Labels: core, ios, java suite, javascript, protocol, review ready

#1005 Revise 0255-Enhance BodyInformation vehicle data
  proposals/0255-Enhance-BodyInformation-vehicle-data.md
Labels: core, hmi, ios, java suite, review ready, review revision update, rpc

#1017 revised SDL-0299
  proposals/0299-Avoid-Deadlock.md
Labels: ios, review ready, review revision update

#1011 Revise SDL 0300 - Voice Assistant App Service
  proposals/0300-Voice-Assistant-App-Service.md
Labels: core, hmi, ios, java suite, javascript, review ready, review revision update, rpc

#1025 Revise SDL-0279 - Screen Manager Subscribe Buttons
  proposals/0279-screen-manager-subscribe-buttons.md
Labels: ios, java suite, javascript, review ready, review revision update

#1003 Revise SDL-0296 - Possibility to update video streaming capabilities during ignition cycle
  assets/proposals/0296-Update-video-streaming-capabilities-during-ignition-cycle/Negotiation_of_VSCs.svg
  assets/proposals/0296-Update-video-streaming-capabilities-during-ignition-cycle/Resolution_Switching.svg
  assets/proposals/0296-Update-video-streaming-capabilities-during-ignition-cycle/sequence_diagram.png
  proposals/0296-Update-video-streaming-capabilities-during-ignition-cycle.md
Labels: core, ios, java suite, review ready, review revision update
