Repository smartdevicelink/sdl_evolution, pull requests merged in 2020-11, with the labels that each got.

#1086 Revise 0315 - Add RPC conflict management
  assets/proposals/0315-Add-RPC-Conflict-Management/Figure1_Conflict_between_ScrollableMessage_and_PerformAudioPassThru.png
  assets/proposals/0315-Add-RPC-Conflict-Management/Figure1_Conflict_between_ScrollableMessage_and_PerformAudioPassThru_1.png
  proposals/0315-Add-RPC-Conflict-Management.md
Labels: core, hmi, review ready, review revision update, sdl policy server

#1041 Improve starting streaming services
  proposals/NNNN-improve-starting-streaming-services.md
Labels: ios, java suite, javascript, review ready

#1092 Revise SDL-0293 Enable OEM exclusive apps support
  proposals/0293-vehicle-type-filter.md
Labels: core, ios, java suite, javascript, protocol, review ready

#1088 Align video streaming parameters with VideoStreamingCapability
  proposals/NNNN-align-VideoStreamingParameter-with-capability.md
Labels: ios, java suite, review ready

#1039 Function to control the priority of audio and video when switching between apps
  assets/proposals/NNNN-Function-to-control-the-priority-of-audio-and-video-when-switching-between-apps/Figure_1_app_switching_sequence.png
  proposals/NNNN-Function-to-control-the-priority-of-audio-and-video-when-switching-between-apps.md
Labels: core, review ready

#1085 Dynamic App list sorting
  assets/proposals/NNNN-Dynamic-App-List-Sorting/Figure1_SDL_App_Icon_display_sequence.PNG
  proposals/NNNN-Dynamic-App-List-Sorting.md
Labels: core, review ready, sdl policy server

#1090 Handle late malformed hmi responses
  assets/proposals/NNNN-handle-late-malformed-hmi-responses/addCommand_fail.png
  assets/proposals/NNNN-handle-late-malformed-hmi-responses/addCommand_fail.txt
  proposals/NNNN-handle-late-malformed-hmi-responses.md
Labels: core, hmi, review ready

#1093 App Library Remote Control Manager
  proposals/nnnn-app-lib-remote-control-manager.md
Labels: ios, java suite, javascript, review ready
