Repository smartdevicelink/sdl_evolution, pull requests merged in 2020-02, with the labels that each got.

#903 Revise SDL-0240 WebEngine Support
  proposals/0240-sdl-js-pwa.md
Labels: core, dev portal/manticore, javascript, review ready, review revision update, rpc, sdl policy server, shaid

#917 Revised SDL-270 - Add means to launch with optimum appHMIType -
  proposals/0270-Add-means-to-launch-with-optimum-appHMIType.md
Labels: core, hmi, ios, java suite, review ready, review revision update, rpc

#877 POI Service Supported
  proposals/NNNN-POI-Service-Supported.md
Labels: core, review ready, rpc

#899 Add Continuous Integration and testing proposal
  assets/proposals/NNNN-Continuous-Integration-And-Testing/ClusterSchema.png
  proposals/NNNN-Continuous-Integration-And-Testing.md
Labels: core, review ready

#907 Screen Manager Template Management
  proposals/nnnn-screenmanager-push-pop.md
Labels: ios, java suite, javascript, review ready

#908 Screen Manager Subscribe Buttons
  proposals/nnnn-screen-manager-subscribe-buttons.md
Labels: ios, java suite, javascript, review ready

#879 Adding new parameter of requiresAudioSupport and BluetoothDeviceAddress
  proposals/NNNN-Adding-new-parameter-of-requiresAudioSupport-and-BluetoothDeviceAddress.md
Labels: core, hmi, ios, java suite, review ready, rpc

#905 Add a mechanism to exclude route guidance between embedded navigation and SDL navigation
  proposals/NNNN-Add-a-mechanism-to-exclude-route-guidance-between-embedded-navigation-and-SDL-navigation.md
Labels: core, hmi, ios, java suite, review ready, rpc

#909 Screen Manager Alert Manager
  proposals/nnnn-screen-manager-alerts.md
Labels: ios, java suite, javascript, review ready

#918 Add Scrollable Message and Slider to Screen Manager
  proposals/nnnn-screen-manager-scrollable-message-and-slider.md
Labels: ios, java suite, javascript, review ready

#920 DialNumber Text
  assets/proposals/NNNN-DialNumber_Text/Current Dial Number.png
  assets/proposals/NNNN-DialNumber_Text/Future Dial Number.png
  proposals/NNNN-DialNumber_Text.md
Labels: core, ios, java suite, review ready, rpc
