Repository smartdevicelink/sdl_evolution, pull requests merged in 2020-10, with the labels that each got.

#1067 Revise SDL-0293 Enable OEM exclusive apps support
  assets/proposals/0293-vehicle-type-filter/OEM_APPS_1.png
  assets/proposals/0293-vehicle-type-filter/OEM_APPS_2.png
  assets/proposals/0293-vehicle-type-filter/OEM_APPS_3.png
  assets/proposals/0293-vehicle-type-filter/OEM_APPS_4.png
  assets/proposals/0293-vehicle-type-filter/sequence_diagram.png
  assets/proposals/NNNN-vehicle-type-filter/android.png
  assets/proposals/NNNN-vehicle-type-filter/ios.png
  assets/proposals/NNNN-vehicle-type-filter/one_noti.png
  assets/proposals/NNNN-vehicle-type-filter/two_noti.png
  proposals/0293-vehicle-type-filter.md
Labels: core, ios, java suite, javascript, protocol, review ready, review revision update

#1078 Revise 0316 - Clarification of transport switching rules and improvement of UX
  assets/proposals/0316-Clarification-of-transport-switching-rules-and-improvement-of-UX/Figure_1_Sequence_with_new_RPC_added_to_existing_logic.png
  assets/proposals/0316-Clarification-of-transport-switching-rules-and-improvement-of-UX/Figure_1_Sequence_with_new_RPC_added_to_existing_logic1.png
  proposals/0316-Clarification-of-transport-switching-rules-and-improvement-of-UX.md
Labels: core, hmi, review ready, review revision update

#1084 Add Current Template Name to Window Capabilities
  proposals/nnnn-window-capabilities-template-name.md
Labels: core, hmi, ios, java suite, javascript, review ready, rpc
