Repository smartdevicelink/sdl_evolution, pull requests merged in 2020-03, with the labels that each got.

#921 ShowConstantTBT Description Update
  proposals/NNNN-ConstantTBT-Update.md
Labels: review ready, rpc

#926 Java Suite Cleanup
  proposals/NNNN-java-suite-cleanup.md
Labels: java suite, review ready

#927 Add Example Apps Github Organization
  proposals/nnnn-example-apps-organization.md
Labels: review ready

#928 Screen Manager Play Audio
  proposals/nnnn-screen-manager-play-audio.md
Labels: ios, java suite, javascript, review ready

#929 Support for Set Language Separately
  proposals/NNNN-set-language-separately.md
Labels: ios, java suite, review ready

#930 Modify the range of APT's maxDuration
  proposals/NNNN-modify-the-range-of-APT's-maxDuration.md
Labels: review ready, rpc

#931 Allows navigation apps to access information about Wi-Fi networks
  proposals/NNNN-allows-navigation-apps-to-access-information-about-Wi-Fi-networks.md
Labels: java suite, review ready

#951 Revise SDL-0234 - Proxy Library RPC Generation proposal
  proposals/0234-proxy-rpc-generation.md
Labels: ios, java suite, review ready, review revision update

#932 Improve VirtualDisplayEncoder for stable frame rate
  assets/proposals/NNNN-improve-VDE-for-stable-frame-rate/vd_mc_unstable.png
  assets/proposals/NNNN-improve-VDE-for-stable-frame-rate/vd_w_intermediate_surface.png
  proposals/NNNN-improve-VDE-for-stable-frame-rate.md
Labels: java suite, review ready

#938 Enable OEM exclusive apps support
  assets/proposals/NNNN-vehicle-type-filter/android.png
  assets/proposals/NNNN-vehicle-type-filter/ios.png
  assets/proposals/NNNN-vehicle-type-filter/one_noti.png
  assets/proposals/NNNN-vehicle-type-filter/two_noti.png
  proposals/NNNN-vehicle-type-filter.md
Labels: core, ios, java suite, protocol, review ready

#940 App Service - Messaging
  proposals/nnnn-app-service-messaging.md
Labels: core, dev portal/manticore, hmi, ios, java suite, review ready, rpc, sdl policy server

#944 Screen Manager Microphone Input Manager
  proposals/nnnn-screen-manager-audio-pass-thru.md
Labels: ios, java suite, javascript, review ready

#952 SDL 0273 WebEngine Projection Mode - Revisions
  proposals/0273-webengine-projection-mode.md
Labels: core, ios, java suite, javascript, review ready, review revision update, rpc, sdl policy server, shaid

#958 Revise SDL-0278 - Screen Manager Template Management
  proposals/0278-screenmanager-layout-management.md
  proposals/0278-screenmanager-push-pop.md
Labels: ios, java suite, javascript, review ready, review revision update

#966 Possibility to update video streaming capabilities during ignition cycle
  assets/proposals/NNNN-Update-video-streaming-capabilities-during-ignition-cycle/sequence_diagram.png
  proposals/NNNN-Update-video-streaming-capabilities-during-ignition-cycle.md
Labels: core, ios, java suite, review ready

#939 Revise SDL-0256 Refactor Fuel Information Related Vehicle Data
  proposals/0256-Refactor-Fuel-Information-Related-Vehicle-Data.md
Labels: core, hmi, ios, java suite, review ready, review revision update, rpc
