Repository smartdevicelink/sdl_evolution, pull requests merged in 2020-08, with the labels that each got.

#1012 Clarification of SDL App Icon display sequence and display order
  assets/proposals/NNNN-Clarification-of-SDL-App-Icon-display-sequence-and-display-order/Figure1_SDL_App_Icon_display_sequence.PNG
  proposals/NNNN-Clarification-of-SDL-App-Icon-display-sequence-and-display-order.md
Labels: core, review ready, sdl policy server

#1056 Revise SDL-0242 Subtle Alert Style - Add SubtleAlert Response
  proposals/0242-alert-style-subtle.md
Labels: accepted with revisions, core, hmi, ios, java suite, javascript, review revision update, rpc, sdl policy server

#1055 Revise SDL-0296 - Possibility to update video streaming capabilities during ignition cycle
  proposals/0296-Update-video-streaming-capabilities-during-ignition-cycle.md
Labels: accepted with revisions, core, hmi, ios, java suite, javascript, review revision update, rpc

#1024 Add RPC Conflict Management
  assets/proposals/NNNN-Add-RPC-Conflict-Management/Figure1_Conflict_between_ScrollableMessage_and_PerformAudioPassThru.png
  assets/proposals/NNNN-Add-RPC-Conflict-Management/Figure2_ONS_RPCs_conflict.png
  assets/proposals/NNNN-Add-RPC-Conflict-Management/Figure3_TTS_RPCs_conflict.png
  assets/proposals/NNNN-Add-RPC-Conflict-Management/Table4_Priority_result_of_Table3.png
  assets/proposals/NNNN-Add-RPC-Conflict-Management/Table_2_Priority_result_of_Table1.png
  proposals/NNNN-Add-RPC-Conflict-Management.md
Labels: core, review ready

#1030 Clarification of transport switching rules and improvement of UX
  assets/proposals/NNNN-Clarification-of-transport-switching-rules-and-improvement-of-UX/Figure_1_Sequence_with_new_RPC_added_to_existing_logic.png
  assets/proposals/NNNN-Clarification-of-transport-switching-rules-and-improvement-of-UX/Table_1_Switching_of_Multiple_Transport.png
  proposals/NNNN-Clarification-of-transport-switching-rules-and-improvement-of-UX.md
Labels: core, hmi, review ready

#1034 SDL Protocol Security Specification
  assets/proposals/NNNN-sdl-protocol-security-specification/tls-handshake.png
  assets/proposals/NNNN-sdl-protocol-security-specification/tls-handshake.uml
  proposals/NNNN-sdl-protocol-security-specification.md
Labels: core, ios, java suite, javascript, protocol, review ready

#1061 App Library: Vehicle Data Manager
  proposals/nnnn-app-lib-vehicle-data-manager.md
Labels: ios, java suite, javascript, review ready

#1073 Revise SDL-0291 Allow navigation apps to access information about WiFi networks
  assets/proposals/0291-allows-navigation-apps-to-access-information-about-Wi-Fi-networks/sequence_diagram.png
  proposals/0291-allows-navigation-apps-to-access-information-about-Wi-Fi-networks.md
Labels: java suite, review ready, review revision update

#1062 SDL-0188 Interior Vehicle Data resumption revision
  proposals/0188-get-interior-data-resumption.md
Labels: accepted, core, hmi, review revision update
