Repository smartdevicelink/sdl_evolution, pull requests merged in 2021-01, with the labels that each got.

#1111 Revise SDL 0267 Main Menu UI Updates
  proposals/0267-addcommand-ui-updates.md
Labels: core, hmi, in review, ios, javascript, rpc

#1115 Revise SDL-0180 - Broaden Choice Uniqueness
  proposals/0180-broaden-choice-uniqueness.md
Labels: accepted, core, in review, ios, java suite, javascript

#1107 Requested Revisions: SDL-0327 App Library Remote Control Manager
  proposals/0327-app-lib-remote-control-manager.md
Labels: ios, java suite, javascript, review ready

#1109 Revise SDL-0305 Homogenize TextFieldName
  proposals/0305-homogenize-textfieldname.md
Labels: core, hmi, in review, ios, java suite, javascript, rpc

#1106 Accepted Revision SDL-0293 Enable OEM exclusive apps support
  proposals/0293-vehicle-type-filter.md
Labels: core, hmi, in review, ios, java suite, javascript, protocol, rpc
