Repository smartdevicelink/sdl_evolution, pull requests merged in 2021-02, with the labels that each got.

#1110 Revise SDL-0282 Screen Manager Alert Manager
  proposals/0282-screen-manager-alerts.md
Labels: accepted, ios, java suite, javascript

#1096 OnDataResumed Notification
  proposals/nnnn-on-data-resumed.md
Labels: core, ios, java suite, javascript, review ready, rpc, sdl policy server, shaid

#1112 App Service Resumption
  proposals/nnnn-app-service-resumption.md
Labels: core, review ready

#1117 Revise SDL-0238 Keyboard Enhancements
  proposals/0238-Keyboard-Enhancements.md
Labels: core, in review, ios, java suite, review revision update, rpc

#1123 Revise 0315 - Add RPC conflict management
  assets/proposals/0315-Add-RPC-Conflict-Management/Table_2_Priority_result_of_Table1.png
  proposals/0315-Add-RPC-Conflict-Management.md
Labels: core, hmi, review ready, sdl policy server
